### PR TITLE
a pull request

### PR DESCRIPTION
**Pull request by DanGrayson**
If any team members get notified about this pull request, let me know!

---

Okay, thanks, several did.

### CODE REVIEW

**Comment by zdorovo** [comment]
I got it!

**Comment by dswinarski** [comment]
Got it!

**Comment by julietteBruce** [comment]
got it.

On May 7, 2016, at 3:44 PM, Daniel R. Grayson <notifications@github.com<mailto:notifications@github.com>> wrote:

If any team members get notified about this pull request, let me know!

---

You can view, comment on, or merge this pull request online at:

  https://github.com/Macaulay2/Workshop-2016-Utah/pull/1

Commit Summary
-   a trivial change

File Changes
-   M README.mdhttps://github.com/Macaulay2/Workshop-2016-Utah/pull/1/files#diff-0 (2)

Patch Links:
-   https://github.com/Macaulay2/Workshop-2016-Utah/pull/1.patch
-   https://github.com/Macaulay2/Workshop-2016-Utah/pull/1.diff

**Comment by coreysharris** [comment]
Got it!

**Comment by tbrysiewicz** [comment]
Got it

**Comment by mnmastro** [comment]
Got it.

**Pull request merged**
